name: AQI Training Pipeline

on:
  schedule:
    - cron: '0 0 * * *'   # roz raat 12 baje (UTC) chalega
  workflow_dispatch:        # manual trigger bhi allow karta hai

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv pandas "hopsworks[python]" scikit-learn joblib

      - name: Run training pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
        run: |
          python trainingpipeline/train_model.py